global:
  # globální nastavení jak často načítat metriky
  scrape_interval: 15s 

scrape_configs:
  # pojmenování metriky, které se bude zobrazovat pro výběr dat
  - job_name: "workshop-1"
    # přepis defaultní URL routy, která je "/metrics" na vlastní
    metrics_path: "/metrics-1.txt"
    static_configs:
      # domený nebo IP adresy odkud se budou metriky sbírat
      - targets: ["host.docker.internal:8081"]
    # přepis globálního nastavení
    scrape_interval: 5s