version: '3'

networks:
  fullcom:
    external: true

services:
  nginx-proxy:  
    container_name: nginx-proxy
    image: nginx:latest
    ports:
      - 8080:80
      - 8081:80
      #- 443:443
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/html/:/usr/share/nginx/html/
      #- ./ssl/:/ssl/
      #- ./psw/:/psw/
    networks:
      - fullcom
      
#  nginx-metrics:
#    container_name: nginx-metrics
#    image: nginx/nginx-prometheus-exporter:0.10.0
#    ports:
#      - 9113:9113
#    command:
#      - -nginx.scrape-uri
#      - http://nginx-proxy/basic_status
#    networks:
#      - fullcom
  
  prometheus:
    container_name: prometheus
    image: bitnami/prometheus:latest
    environment:
      - TZ=Europe/Prague
    volumes:
      - ./prometheus/conf/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - fullcom

  grafana:
    container_name: "grafana"
    image: grafana/grafana:8.5.27
    ports:
      - 3000:3000
    env_file:
      - 'env.grafana'
    # volumes:
    #   - ./grafana/etc/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - fullcom