services:

  nginx-proxy:  
    container_name: nginx-proxy
    image: nginx:latest
    ports:
      - 8080:80
      #- 443:443
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/html/:/usr/share/nginx/html/
      #- ./ssl/:/ssl/
      #- ./psw/:/psw/
    networks:
      - pilif-net
      
#  nginx-metrics:
#    container_name: nginx-metrics
#    image: nginx/nginx-prometheus-exporter:0.10.0
#    ports:
#      - 9113:9113
#    command:
#      - -nginx.scrape-uri
#      - http://nginx-proxy/basic_status
#    networks:
#      - pilif-net
  
  prometheus:
    container_name: prometheus
    image: bitnami/prometheus:latest
    environment:
      - TZ=Europe/Prague
    volumes:
      - ./prometheus/conf/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - pilif-net 
     
networks:
  pilif-net:
    driver: bridge       